/** Legend annotation: arrow + label (normalized coordinates 0–1) */
export interface Legend {
  label: string;
  fleche: { x1: number; y1: number; x2: number; y2: number };
}

/** An imaging image (X-ray/MRI) with its legends generated by the LLM */
export interface LegendItem {
  imageUrl: string;
  legendes?: Legend[];
}

/** Output of the backend pipeline (POST /api/report/understand) */
export interface ReportPipelineResult {
  extraction?: ExtractedFacts;
  vulgarization?: string;
  validationOk?: boolean;
  questions?: string[];
  /** Imaging images (X-ray/MRI) added by the patient, with legends (arrows) — linked to the simplified explanation */
  legendItems?: LegendItem[];
}

/** Partial result (streaming): each field can arrive progressively */
export type ReportPipelineResultPartial = Partial<ReportPipelineResult>;

/** Patient context question (adapted to the type of exam) */
export interface ContextQuestion {
  id: string;
  label: string;
}

/** Patient's answers to context questions (id → answer) */
export type PatientContext = Record<string, string>;

export interface ExtractedFacts {
  localisation?: string;
  type_examen?: string;
  faits_principaux?: string[];
  termes_techniques?: string[];
  conclusion_rapport?: string;
  niveau_urgence?: "normal" | "follow-up" | "urgent";
}
